### ISSUE TITLE
Add redis persistence

### ISSUE THREAD

**Issue by fabio-ivona** [defstudio/dock#1]
```
redis_db:
        container_name: redis_db
        command: bash -c "redis-server --appendonly yes --requirepass <password>"
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis-volume:/data
```
